name: Unit tests

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'
        check-latest: true
        cache: true

    - name: Run build target
      run: make build

    - name: Run test target
      run: make test
